In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 25.1 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 49.0 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.2 pandas-3.0.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [31]:
# Dataframes -> tablas en memoria similares a las de una base de datos
# Dataframe -> Listas, Diccionarios, tuplas
import pandas as pd

data = {
    'Nombre': ['Juan', 'Carlos', 'Pedro'],
    'Edad': [25, 30, 35]
}

df = pd.DataFrame(data)

In [32]:
df

   Nombre  Edad
0    Juan    25
1  Carlos    30
2   Pedro    35

In [33]:
df = pd.read_csv('./data/data.csv')
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [34]:
df = pd.read_csv('./data/data', sep='|')
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [35]:
df = pd.read_csv('./data/data_without_header', header=None, names=['nombre', 'edad', 'ciudad'])
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [36]:
df = pd.read_json('./data/data.json')
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [37]:
df = pd.read_csv('./data/sales_data_sample.csv', encoding='ISO-8859-1')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [38]:
# head

df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [39]:
df.tail()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [40]:
df.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [41]:
df.index

RangeIndex(start=0, stop=2823, step=1)

In [42]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [43]:
df[['ORDERNUMBER', 'PRICEEACH', 'SALES']]

      ORDERNUMBER  PRICEEACH    SALES
0           10107      95.70  2871.00
1           10121      81.35  2765.90
2           10134      94.74  3884.34
3           10145      83.26  3746.70
4           10159     100.00  5205.27
...           ...        ...      ...
2818        10350     100.00  2244.40
2819        10373     100.00  3978.51
2820        10386     100.00  5417.57
2821        10397      62.24  2116.16
2822        10414      65.52  3079.44

[2823 rows x 3 columns]

In [14]:
df.loc[0]

ORDERNUMBER                           10107
QUANTITYORDERED                          30
PRICEEACH                              95.7
ORDERLINENUMBER                           2
SALES                                2871.0
ORDERDATE                    2/24/2003 0:00
STATUS                              Shipped
QTR_ID                                    1
MONTH_ID                                  2
YEAR_ID                                2003
PRODUCTLINE                     Motorcycles
MSRP                                     95
PRODUCTCODE                        S10_1678
CUSTOMERNAME              Land of Toys Inc.
PHONE                            2125557818
ADDRESSLINE1        897 Long Airport Avenue
ADDRESSLINE2                            NaN
CITY                                    NYC
STATE                                    NY
POSTALCODE                            10022
COUNTRY                                 USA
TERRITORY                               NaN
CONTACTLASTNAME                          Yu
CONTACTFIRSTNAME                       Kwai
DEALSIZE                              Small
Name: 0, dtype: object

In [15]:
df.loc[[1,5]]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

In [17]:
df[df['QTR_ID'] == 2].head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
11,10237,23,100.00,7,2333.12,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,NaN,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,NaN,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
24,10403,24,100.00,7,2434.56,4/8/2005 0:00,Shipped,2,4,2005,...,Berkeley Gardens 12 Brewery,NaN,Liverpool,NaN,WX1 6LT,UK,EMEA,Devon,Elizabeth,Small

In [18]:
df.query("STATE == 'NY' and QTR_ID == 1")

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
54,10107,39,99.91,5,3896.49,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
80,10107,27,100.00,4,6065.55,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
240,10107,21,100.00,1,3036.60,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
475,10102,39,100.00,2,4808.31,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Medium
501,10102,41,50.14,1,2055.74,1/10/2003 0:00,Shipped,1,1,2003,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
804,10107,29,70.87,6,2055.23,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1466,10107,25,100.00,3,2845.75,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1564,10107,38,83.03,7,3155.14,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Medium
2173,10107,20,92.90,8,1858.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small

In [19]:
df.filter(like = 'ID')

      QTR_ID  MONTH_ID  YEAR_ID
0          1         2     2003
1          2         5     2003
2          3         7     2003
3          3         8     2003
4          4        10     2003
...      ...       ...      ...
2818       4        12     2004
2819       1         1     2005
2820       1         3     2005
2821       1         3     2005
2822       2         5     2005

[2823 rows x 3 columns]

In [20]:
total_nulos = df.isnull().sum().sort_values(ascending=False)
total_nulos

ADDRESSLINE2        2521
STATE               1486
TERRITORY           1074
POSTALCODE            76
SALES                  0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
ORDERNUMBER            0
MONTH_ID               0
QTR_ID                 0
STATUS                 0
ORDERDATE              0
PRODUCTCODE            0
YEAR_ID                0
MSRP                   0
PRODUCTLINE            0
ADDRESSLINE1           0
PHONE                  0
CUSTOMERNAME           0
CITY                   0
COUNTRY                0
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [ ]:
df['ADDRESSLINE2'] = df['ADDRESSLINE2'].fillna('-')

In [22]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,-,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,-,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,-,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,-,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,-,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [23]:
df[['QTR_ID', 'SALES', 'STATE']].groupby(['QTR_ID','STATE']).sum()

                          SALES
QTR_ID STATE
1      CA             567351.70
       Isle of Wight   26906.68
       MA             101836.44
       NH              12133.25
       NJ               8722.12
       NSW             65012.42
       NY              32647.81
       Osaka           50490.64
       PA              27398.82
       Queensland      21730.03
       Tokyo           38191.39
       Victoria        49637.57
2      BC              31302.50
       CA             167272.02
       CT             133103.25
       MA              96652.51
       NJ              74506.07
       NSW             43971.43
       NV              33847.62
       NY             165100.34
       Osaka           17114.43
       PA              13454.04
       Quebec          58257.50
       Tokyo           26482.70
       Victoria        74513.93
3      BC              43332.35
       CA             348205.38
       CT               7600.12
       MA             224886.29
       NSW            116886.16
       NV              34453.85
       NY              63027.92
       PA              71930.61
       Queensland      10640.29
       Victoria        12334.82
4      BC              75238.92
       CA             422713.13
       CT              97957.91
       Isle of Wight   51334.16
       MA             243068.48
       NH             119552.05
       NSW             79697.10
       NV              14449.61
       NY             385567.69
       PA             160543.80
       Quebec          15947.29
       Queensland      27098.80
       Tokyo           55888.65
       Victoria       129100.55

In [24]:
df[['STATE', 'SALES']] \
    .groupby('STATE', as_index=False) \
    .mean() \
    .sort_values(by='SALES', ascending=False) \
    .head(5)

         STATE        SALES
13  Queensland  3964.608000
6           NJ  3963.247143
2           CT  3912.480000
5           NH  3873.097059
14       Tokyo  3767.585625

In [25]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,-,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,-,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,-,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,-,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,-,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [26]:
# dropna -> Elimina filas con datos nulos
# drop_duplicates()
df.drop_duplicates(subset=['STATE'])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,-,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,-,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,-,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,-,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,-,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,-,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium
18,10318,46,94.74,1,4358.04,11/2/2004 0:00,Shipped,4,11,2004,...,7586 Pompton St.,-,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium
21,10361,20,72.55,13,1451.00,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
32,10174,34,100.00,4,8014.82,11/6/2003 0:00,Shipped,4,11,2003,...,31 Duncan St. West End,-,South Brisbane,Queensland,4101,Australia,APAC,Calaghan,Tony,Large
35,10206,47,100.00,6,9064.89,12/5/2003 0:00,Shipped,4,12,2003,...,1900 Oak St.,-,Vancouver,BC,V3F 2K1,Canada,NaN,Tannamuri,Yoshi,Large
39,10258,32,100.00,6,7680.64,6/15/2004 0:00,Shipped,2,6,2004,...,2-2-8 Roppongi,-,Minato-ku,Tokyo,106-0032,Japan,Japan,Shimamura,Akiko,Large
45,10322,40,100.00,1,6000.40,11/4/2004 0:00,Shipped,4,11,2004,...,2304 Long Airport Avenue,-,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
52,10411,23,100.00,9,4140.23,5/1/2005 0:00,Shipped,2,5,2005,...,43 rue St. Laurent,-,Montreal,Quebec,H1J 1C3,Canada,NaN,Fresnisre,Jean,Medium
63,10210,23,100.00,2,3009.09,1/12/2004 0:00,Shipped,1,1,2004,...,"Dojima Avanza 4F, 1-6-20 Dojima, Kita-ku",-,Osaka,Osaka,530-0003,Japan,Japan,Kentary,Mory,Medium
123,10316,33,100.00,17,4128.96,11/1/2004 0:00,Shipped,4,11,2004,...,Garden House Crowther Way,-,Cowes,Isle of Wight,PO31 7PJ,UK,EMEA,Bennett,Helen,Medium
462,10278,34,100.00,6,4667.86,8/6/2004 0:00,Shipped,3,8,2004,...,8489 Strong St.,-,Las Vegas,NV,83030,USA,NaN,King,Sue,Medium

In [27]:
df.duplicated(subset=['QTR_ID','STATE']).tail(50)

2773    True
2774    True
2775    True
2776    True
2777    True
2778    True
2779    True
2780    True
2781    True
2782    True
2783    True
2784    True
2785    True
2786    True
2787    True
2788    True
2789    True
2790    True
2791    True
2792    True
2793    True
2794    True
2795    True
2796    True
2797    True
2798    True
2799    True
2800    True
2801    True
2802    True
2803    True
2804    True
2805    True
2806    True
2807    True
2808    True
2809    True
2810    True
2811    True
2812    True
2813    True
2814    True
2815    True
2816    True
2817    True
2818    True
2819    True
2820    True
2821    True
2822    True
dtype: bool

In [ ]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,-,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,-,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,-,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,-,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,-,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",-,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,-,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",-,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,-,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,-,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
df = df.drop_duplicates(subset=['STATE'])

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,-,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,-,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,-,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
10,10223,37,100.00,1,3965.66,2/20/2004 0:00,Shipped,1,2,2004,...,636 St Kilda Road,Level 3,Melbourne,Victoria,3004,Australia,APAC,Ferguson,Peter,Medium
12,10251,28,100.00,2,3188.64,5/18/2004 0:00,Shipped,2,5,2004,...,7476 Moss Rd.,-,Newark,NJ,94019,USA,NaN,Brown,William,Medium
13,10263,34,100.00,2,3676.76,6/28/2004 0:00,Shipped,2,6,2004,...,25593 South Bay Ln.,-,Bridgewater,CT,97562,USA,NaN,King,Julie,Medium
15,10285,36,100.00,6,4099.68,8/27/2004 0:00,Shipped,3,8,2004,...,39323 Spinnaker Dr.,-,Cambridge,MA,51247,USA,NaN,Hernandez,Marta,Medium
18,10318,46,94.74,1,4358.04,11/2/2004 0:00,Shipped,4,11,2004,...,7586 Pompton St.,-,Allentown,PA,70267,USA,NaN,Yu,Kyung,Medium
21,10361,20,72.55,13,1451.00,12/17/2004 0:00,Shipped,4,12,2004,...,"Monitor Money Building, 815 Pacific Hwy",Level 6,Chatswood,NSW,2067,Australia,APAC,Huxley,Adrian,Small
32,10174,34,100.00,4,8014.82,11/6/2003 0:00,Shipped,4,11,2003,...,31 Duncan St. West End,-,South Brisbane,Queensland,4101,Australia,APAC,Calaghan,Tony,Large
35,10206,47,100.00,6,9064.89,12/5/2003 0:00,Shipped,4,12,2003,...,1900 Oak St.,-,Vancouver,BC,V3F 2K1,Canada,NaN,Tannamuri,Yoshi,Large
39,10258,32,100.00,6,7680.64,6/15/2004 0:00,Shipped,2,6,2004,...,2-2-8 Roppongi,-,Minato-ku,Tokyo,106-0032,Japan,Japan,Shimamura,Akiko,Large
45,10322,40,100.00,1,6000.40,11/4/2004 0:00,Shipped,4,11,2004,...,2304 Long Airport Avenue,-,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
52,10411,23,100.00,9,4140.23,5/1/2005 0:00,Shipped,2,5,2005,...,43 rue St. Laurent,-,Montreal,Quebec,H1J 1C3,Canada,NaN,Fresnisre,Jean,Medium
63,10210,23,100.00,2,3009.09,1/12/2004 0:00,Shipped,1,1,2004,...,"Dojima Avanza 4F, 1-6-20 Dojima, Kita-ku",-,Osaka,Osaka,530-0003,Japan,Japan,Kentary,Mory,Medium
123,10316,33,100.00,17,4128.96,11/1/2004 0:00,Shipped,4,11,2004,...,Garden House Crowther Way,-,Cowes,Isle of Wight,PO31 7PJ,UK,EMEA,Bennett,Helen,Medium
462,10278,34,100.00,6,4667.86,8/6/2004 0:00,Shipped,3,8,2004,...,8489 Strong St.,-,Las Vegas,NV,83030,USA,NaN,King,Sue,Medium

In [51]:
df_copy = df.copy()

In [52]:
df_copy['SALES3'] = df_copy['SALES']*2

In [55]:
df_copy

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,SALES2,SALES3
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,5742.00,5742.00
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,5531.80,5531.80
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,7768.68,7768.68
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,7493.40,7493.40
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,10410.54,10410.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small,4488.80,4488.80
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium,7957.02,7957.02
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium,10835.14,10835.14
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small,4232.32,4232.32
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium,6158.88,6158.88

In [54]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,SALES2
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,5742.00
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,5531.80
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,7768.68
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,7493.40
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,10410.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small,4488.80
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium,7957.02
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium,10835.14
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small,4232.32
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium,6158.88